### ISSUE TITLE
storage: panic on broken pipe

### ISSUE THREAD

**Issue by kurin** [GoogleCloudPlatform/gcloud-golang#250]
I have a fairly simple program that gets a storage.Writer and then tries to shove 200GB into GCS Nearline over my poor 5Mb connection.  Currently the connection always gets reset, which is probably TWC's fault, but when it happens I get the following panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0x6eef27]

goroutine 9 [running]:
panic(0x8e6360, 0xc820010140)
        /home/kurin/go/src/runtime/panic.go:464 +0x3e6
google.golang.org/api/gensupport.(*ResumableUpload).transferChunks(0xc8209b6660, 0x800c665a8, 0xc820010390, 0xc82010e401, 0x0, 0x0)
        /home/kurin/gopath/src/google.golang.org/api/gensupport/resumable.go:89 +0x617
google.golang.org/api/gensupport.(*ResumableUpload).Upload(0xc8209b6660, 0x800c665a8, 0xc820010390, 0xc82010e480, 0x0, 0x0)
        /home/kurin/gopath/src/google.golang.org/api/gensupport/resumable.go:114 +0x5e
google.golang.org/api/storage/v1.(*ObjectsInsertCall).Do(0xc820014bd0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/kurin/gopath/src/google.golang.org/api/storage/v1/storage-gen.go:6111 +0x54c
google.golang.org/cloud/storage.(*Writer).open.func1(0xc82000da00, 0xc820094780, 0xc82002e480, 0x0, 0x0, 0x0)
        /home/kurin/gopath/src/google.golang.org/cloud/storage/writer.go:75 +0x4c3
created by google.golang.org/cloud/storage.(*Writer).open
        /home/kurin/gopath/src/google.golang.org/cloud/storage/writer.go:83 +0x555
```

The line that corresponds to is:

```go
success := err == nil && res.StatusCode == statusResumeIncomplete || res.StatusCode == http.StatusOK
```

I suspect what's happening is that this is interpreted as

```go
(err == nil && res.StatusCode == statusResumeIncomplete) || res.StatusCode == http.StatusOK
```

but that the author intended

```go
err == nil && (res.StatusCode == statusResumeIncomplete || res.StatusCode == http.StatusOK)
```

I'll submit a CL that de-clevers this line; but if you really like it let me know and I'll just throw in the parens.

**Comment by broady** [comment]
de-clevering would be much appreciated.

**Comment by kurin** [comment]
Actually, nevermind, I was using an ancient fetch of this package.  Good work everyone, I feel like we discovered some important learnings today.

**Comment by kurin** [comment]
![image](https://user-images.githubusercontent.com/90267/106512218-2ab78e80-6486-11eb-942c-1a35c6afa804.png)
