### ISSUE TITLE
datastore: Count panic / timeouts

### ISSUE THREAD

**Issue by Nitecon** [GoogleCloudPlatform/gcloud-golang#268]
Datastore go package appears to be crashing when doing a cli.Count() on any query.  Due to this issue I'm having to iterate through all records to get a full count of items that currently exist, this would normally not be an issue however we have 400k + records so iterating over 400k (will grow exponentially over time) records defeats the purpose of the limit / offset, and it appears to be timing out.  The test is very simple and as long as I remove the Count returns in sub 2 second, with the count it times out after 30 secs in a test and will run for what feels like hours in a browser query.

go version go1.6 darwin/amd64
Latest version of datastore etc pulled with go get -u 

The test is very simple and nowhere near complete but useful for illustration: 
```go
func TestGetFullLog(t *testing.T) {
	t.Parallel()
        // Params are limit & offset
	d, total, err := GetFullList(20, 0)
	if err != nil {
		t.Errorf("Test failed to get data")
	}
	if len(d) <= 0 {
		t.Errorf("We should have more than 0 items len(%d) total: %d", len(d), total)
	}
}
```
The problematic function is: 
```go
func getTotal(q *datastore.Query) (int, error) {
	cli, ctx, err := getClient()
	if err != nil {
		log.Printf("Error trying to get ds client: %s", err)
		return 0, err
	}
	defer cli.Close()
	return cli.Count(ctx, q)
}
```

I separated out getTotal to do a test and as long as that function is excluded it all works just fine. Passing in the client / context does not make a difference.  Having the cli.Close() deferred makes no difference anywhere else either. 

```
panic: test timed out after 30s

goroutine 27 [running]:
panic(0x5c7f60, 0xc8200d9120)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x9443e8, 0xb95060, 0x3, 0x3, 0x1)
	/usr/local/go/src/testing/testing.go:603 +0x564
testing.(*M).Run(0xc8203cff08, 0xf)
	/usr/local/go/src/testing/testing.go:515 +0x81
git.internal.net/DSV/audit.TestMain(0xc8203cff08)
	/data/go/src/git.internal.net/DSV/audit/main_test.go:11 +0x80
main.main()
	git.internal.net/DSV/audit/_test/_testmain.go:56 +0x114

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [select]:
google.golang.org/grpc/transport.(*Stream).Header(0xc8204e4d20, 0xc8204e4d20, 0x0, 0x0)
	/data/go/src/google.golang.org/grpc/transport/transport.go:221 +0x242
google.golang.org/grpc.recvResponse(0x18c2c40, 0xbbb378, 0x0, 0x0, 0x0, 0x0, 0x18c2c78, 0xc820190440, 0x18c2ca0, 0xc820190460, ...)
	/data/go/src/google.golang.org/grpc/call.go:54 +0x4e
google.golang.org/grpc.Invoke(0x1848a00, 0xc8201dfde0, 0x8bb600, 0x2c, 0x797d00, 0xc8204cc3c0, 0x7638a0, 0xc8200d8f10, 0xc820658000, 0x0, ...)
	/data/go/src/google.golang.org/grpc/call.go:178 +0xae6
google.golang.org/cloud/datastore/internal/proto.(*datastoreClient).RunQuery(0xc8205aa018, 0x1848a00, 0xc8201dfde0, 0xc8204cc3c0, 0x0, 0x0, 0x0, 0xc820320140, 0x0, 0x0)
	/data/go/src/google.golang.org/cloud/datastore/internal/proto/datastore.pb.go:988 +0xec
google.golang.org/cloud/datastore.callNext(0x1848a00, 0xc8201dfde0, 0xc820010e80, 0xc8204cc3c0, 0xc820320140, 0x0, 0xc820320140, 0x0, 0x0)
	/data/go/src/google.golang.org/cloud/datastore/query.go:466 +0x2b5
google.golang.org/cloud/datastore.(*Client).Count(0xc820010e80, 0x1848a00, 0xc8201dfde0, 0xc82075bcc8, 0x0, 0x0, 0x0)
	/data/go/src/google.golang.org/cloud/datastore/query.go:447 +0x56d
git.internal.net/DSV/audit.getTotal(0xc820016240, 0x0, 0x0, 0x0)
	/data/go/src/git.internal.net/DSV/audit/audit.go:89 +0x3a6
git.internal.net/DSV/audit.GetFullAuditLog(0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/git.internal.net/DSV/audit/audit.go:183 +0x361
git.internal.net/DSV/audit.TestGetFullLog(0xc820086a20)
	/data/go/src/git.internal.net/DSV/audit/audit_test.go:11 +0x59
testing.tRunner(0xc820086a20, 0xb95060)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 9 [chan receive]:
testing.RunTests.func1(0xc82001b920, 0xc820086a20)
	/usr/local/go/src/testing/testing.go:586 +0x47
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:587 +0x933

goroutine 10 [select]:
google.golang.org/grpc/transport.(*Stream).Header(0xc8204e4e00, 0xc8204e4e00, 0x0, 0x0)
	/data/go/src/google.golang.org/grpc/transport/transport.go:221 +0x242
google.golang.org/grpc.recvResponse(0x18c2c40, 0xbbb378, 0x0, 0x0, 0x0, 0x0, 0x18c2c78, 0xc82044e5a0, 0x18c2ca0, 0xc82044e5e0, ...)
	/data/go/src/google.golang.org/grpc/call.go:54 +0x4e
google.golang.org/grpc.Invoke(0x1848a00, 0xc8201dfde0, 0x8bb600, 0x2c, 0x797d00, 0xc82042e420, 0x7638a0, 0xc8200d9080, 0xc8202b4000, 0x0, ...)
	/data/go/src/google.golang.org/grpc/call.go:178 +0xae6
google.golang.org/cloud/datastore/internal/proto.(*datastoreClient).RunQuery(0xc82023a1c0, 0x1848a00, 0xc8201dfde0, 0xc82042e420, 0x0, 0x0, 0x0, 0xc8200d8cc0, 0x0, 0x0)
	/data/go/src/google.golang.org/cloud/datastore/internal/proto/datastore.pb.go:988 +0xec
google.golang.org/cloud/datastore.callNext(0x1848a00, 0xc8201dfde0, 0xc82036c240, 0xc82042e420, 0xc8200d8cc0, 0x0, 0xc8200d8cc0, 0x0, 0x0)
	/data/go/src/google.golang.org/cloud/datastore/query.go:466 +0x2b5
google.golang.org/cloud/datastore.(*Client).Count(0xc82036c240, 0x1848a00, 0xc8201dfde0, 0xc820757cb0, 0xc8201cc720, 0x0, 0x0)
	/data/go/src/google.golang.org/cloud/datastore/query.go:447 +0x56d
git.internal.net/DSV/audit.getTotal(0xc8203cc240, 0x0, 0x0, 0x0)
	/data/go/src/git.internal.net/DSV/audit/audit.go:89 +0x3a6
git.internal.net/DSV/audit.GetFullAuditLogByID(0x1, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/git.internal.net/DSV/audit/audit.go:209 +0x3c5
git.internal.net/DSV/audit.TestFullAuditLogById(0xc820086ab0)
	/data/go/src/git.internal.net/DSV/audit/audit_test.go:23 +0x62
testing.tRunner(0xc820086ab0, 0xb95078)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 11 [chan receive]:
testing.RunTests.func1(0xc82001b920, 0xc820086ab0)
	/usr/local/go/src/testing/testing.go:586 +0x47
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:587 +0x933

goroutine 48 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc82039e2d0)
	/data/go/src/google.golang.org/grpc/clientconn.go:547 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc82039e2d0)
	/data/go/src/google.golang.org/grpc/clientconn.go:355 +0x1b5
created by google.golang.org/grpc.NewConn
	/data/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3

goroutine 46 [IO wait]:
net.runtime_pollWait(0x184eb38, 0x72, 0xc8202ee800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820369800, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820369800, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203697a0, 0xc8202ee800, 0x400, 0x400, 0x0, 0x1840050, 0xc820014068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200300d0, 0xc8202ee800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820370a50, 0x184ecb8, 0xc8200300d0, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820462900, 0x944c17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820462900, 0xc8203d6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x1856950, 0xc820462900, 0xc8205f06e8, 0xc8203d6000, 0x1000, 0x1000, 0x5ef3, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc8202f4440, 0xc8203d6000, 0x1000, 0x1000, 0xc82004dd0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc82057a300)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82057a300, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8205f0680)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 41 [IO wait]:
net.runtime_pollWait(0x184ebf8, 0x72, 0xc8202e7000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820368990, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820368990, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820368930, 0xc8202e7000, 0x1000, 0x1000, 0x0, 0x1840050, 0xc820014068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820030338, 0xc8202e7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82038a0f0, 0x184ecb8, 0xc820030338, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820386600, 0x944c17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820386600, 0xc82038d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0x1856950, 0xc820386600, 0xc82033afd8, 0xc82038d000, 0x1000, 0x1000, 0x5ef3, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc8202f4540, 0xc82038d000, 0x1000, 0x1000, 0xc82004fd0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc82036e600)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82036e600, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82033af70)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 42 [select]:
net/http.(*persistConn).writeLoop(0xc82033af70)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 19 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8201c24b0)
	/data/go/src/google.golang.org/grpc/clientconn.go:547 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8201c24b0)
	/data/go/src/google.golang.org/grpc/clientconn.go:355 +0x1b5
created by google.golang.org/grpc.NewConn
	/data/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3

goroutine 47 [select]:
net/http.(*persistConn).writeLoop(0xc8205f0680)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 22 [IO wait]:
net.runtime_pollWait(0x184ea78, 0x72, 0xc8203ab000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202045a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202045a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820204540, 0xc8203ab000, 0x1000, 0x1000, 0x0, 0x1840050, 0xc820014068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200300d8, 0xc8203ab000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8204cc660, 0x184ecb8, 0xc8200300d8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820386000, 0x944c17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820386000, 0xc8203e6000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc82036f3e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc82036f3e0, 0xc820016db8, 0x9, 0x9, 0x7ff7, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x1849b40, 0xc82036f3e0, 0xc820016db8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x1849b40, 0xc82036f3e0, 0xc820016db8, 0x9, 0x9, 0xc8203764ec, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc820016db8, 0x9, 0x9, 0x1849b40, 0xc82036f3e0, 0x20000000, 0x0, 0x0, 0x0)
	/data/go/src/golang.org/x/net/http2/frame.go:237 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc820016d80, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/golang.org/x/net/http2/frame.go:464 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8204cd6e0, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc8201c25a0)
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:791 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:174 +0xd21

goroutine 23 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc8201c25a0)
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:869 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:201 +0x15c2

goroutine 67 [IO wait]:
net.runtime_pollWait(0x184e9b8, 0x72, 0xc8204df000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82020c5a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82020c5a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82020c540, 0xc8204df000, 0x1000, 0x1000, 0x0, 0x1840050, 0xc820014068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82023a1b0, 0xc8204df000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201cc990, 0x184ecb8, 0xc82023a1b0, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820462000, 0x944c17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820462000, 0xc820536000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc82057b140)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc82057b140, 0xc8203cc7b8, 0x9, 0x9, 0x7ff7, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x1849b40, 0xc82057b140, 0xc8203cc7b8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x1849b40, 0xc82057b140, 0xc8203cc7b8, 0x9, 0x9, 0xc8201b692c, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc8203cc7b8, 0x9, 0x9, 0x1849b40, 0xc82057b140, 0x20000000, 0x0, 0x0, 0x0)
	/data/go/src/golang.org/x/net/http2/frame.go:237 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc8203cc780, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/golang.org/x/net/http2/frame.go:464 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201cda10, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc82039e3c0)
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:791 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:174 +0xd21

goroutine 68 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc82039e3c0)
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:869 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:201 +0x15c2

goroutine 82 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8201442d0)
	/data/go/src/google.golang.org/grpc/clientconn.go:547 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8201442d0)
	/data/go/src/google.golang.org/grpc/clientconn.go:355 +0x1b5
created by google.golang.org/grpc.NewConn
	/data/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3

goroutine 85 [IO wait]:
net.runtime_pollWait(0x184e8f8, 0x72, 0xc820543000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201e44c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201e44c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201e4460, 0xc820543000, 0x1000, 0x1000, 0x0, 0x1840050, 0xc820014068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82023a210, 0xc820543000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82042e6c0, 0x184ecb8, 0xc82023a210, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820386300, 0x944c17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820386300, 0xc8203a0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc820258fc0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820258fc0, 0xc8201e63f8, 0x9, 0x9, 0x7ff7, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x1849b40, 0xc820258fc0, 0xc8201e63f8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x1849b40, 0xc820258fc0, 0xc8201e63f8, 0x9, 0x9, 0xc820141aac, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc8201e63f8, 0x9, 0x9, 0x1849b40, 0xc820258fc0, 0x20000000, 0x0, 0x0, 0x0)
	/data/go/src/golang.org/x/net/http2/frame.go:237 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc8201e63c0, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/golang.org/x/net/http2/frame.go:464 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc82042f920, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc8201443c0)
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:791 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:174 +0xd21

goroutine 86 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc8201443c0)
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:869 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:201 +0x15c2

goroutine 24 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8206482d0)
	/data/go/src/google.golang.org/grpc/clientconn.go:547 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8206482d0)
	/data/go/src/google.golang.org/grpc/clientconn.go:355 +0x1b5
created by google.golang.org/grpc.NewConn
	/data/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3

goroutine 69 [runnable]:
crypto/tls.(*fixedNonceAEAD).Overhead(0xc820011cc0, 0xc82010a000)
	/usr/local/go/src/crypto/tls/cipher_suites.go:147
crypto/tls.(*halfConn).decrypt(0xc82066c0e0, 0xc8204cc840, 0x2c, 0xc8204cc840, 0xc8204cc870)
	/usr/local/go/src/crypto/tls/conn.go:274 +0x8d9
crypto/tls.(*Conn).readRecord(0xc82066c000, 0x944c17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:619 +0x160b
crypto/tls.(*Conn).Read(0xc82066c000, 0xc820688000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc820550cc0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820550cc0, 0xc820698038, 0x9, 0x9, 0x7ff7, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x1849b40, 0xc820550cc0, 0xc820698038, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x1849b40, 0xc820550cc0, 0xc820698038, 0x9, 0x9, 0xc82014194c, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc820698038, 0x9, 0x9, 0x1849b40, 0xc820550cc0, 0x20000000, 0x0, 0x0, 0x0)
	/data/go/src/golang.org/x/net/http2/frame.go:237 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc820698000, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/golang.org/x/net/http2/frame.go:464 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8202de000, 0x0, 0x0, 0x0, 0x0)
	/data/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc8204dc870)
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:791 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:174 +0xd21

goroutine 70 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc8204dc870)
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:869 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/data/go/src/google.golang.org/grpc/transport/http2_client.go:201 +0x15c2
exit status 2
FAIL	git.internal.net/DSV/audit	30.060s
```

**Comment by okdave** [comment]
Does `Count` panic, or does it just take too long to return? The snippet you've provided above indicates that the test itself is timing out, and not that the panic is originating in the datastore code.

The [underlying datastore API](https://cloud.google.com/datastore/reference/rpc/google.datastore.v1beta3#index) has no Count method, so the Count method for the Query works by [paging through all the available results](https://github.com/GoogleCloudPlatform/gcloud-golang/blob/master/datastore/query.go#L411). If you have 400k+ entities, then it is going to hang forever. You will need to find another solution if you need an accurate count for so many entries.

I think we can do a better job with documentation here. The [python reference for Count](https://cloud.google.com/appengine/docs/python/datastore/queryclass#Contents) explicitly calls this out.

**Comment by Nitecon** [comment]
Thanks @okdave just as a FYI this never completed even with only 1500 entities

**Comment by okdave** [comment]
1500 is more concerning. It definitely should for that. I'll take another look.

**Comment by Nitecon** [comment]
@okdave if you need me to run additional tests etc feel free to let me know.  I've tried to do a manual count which does work by using the cursor to iterate over all objects but this is obviously incredibly slow as it attempts to marshall the data instead of just counting items in the current slice, it is however faster than an actual count which never completes though.

**Comment by okdave** [comment]
Thanks @Nitecon – I've tracked down the bug and completely rewritten it all. Sorry that I wasn't able to repro it earlier.
